# 1.numpy入门

In [ ]:
# 导入
import numpy as  np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

# 2.numpy的属性

In [ ]:
arr = np.arange(15).reshape((3,5))
print(f'ndarray对象:{arr}')
print(f'数组的形状（维度）：{arr.shape}')
print(f'数组的轴：{arr.ndim}')
print(f'数组的长度{arr.size}')
print(f'数组每个元素的类型{arr.dtype}')
print(f'数组的每个元素的大小（字节数）:{arr.itemsize}')
print(f'数组的类型：{type(arr)}')

# 3.创建ndarray对象

## 3.1把python数组封装成ndarray对象


In [ ]:
arr1 = np.array([1,2,3,4])
print(f'数组对象：{arr1}')
print(f'数组类型：{type(arr1)}')
print(f'数组元素类型：{arr1.dtype}')


## 3.2 zeros()/ones()/empty() 函数创建ndarray对象


In [ ]:
# zeros() 创建全是0的数组，即ndarray对象
arr2 = np.zeros((2,3))
print(f'数组对象：{arr2}')
print(f'数组类型：{type(arr2)}')
print(f'数组元素类型：{arr2.dtype}')

In [ ]:
# ones
arr3 = np.ones((2,3,4))
print(f'数组对象：{arr3}')
print(f'数组类型：{type(arr3)}')
print(f'数组元素类型：{arr3.dtype}')

In [ ]:
# empty:创建内容随机并且依赖内容状态的随机值
arr4 = np.empty((2,3))
print(f'数组对象：{arr4}')
print(f'数组类型：{type(arr4)}')
print(f'数组元素类型：{arr4.dtype}')

## 3.3arange()函数，创建ndarray对象

In [ ]:
# arrange(起始值，结束值，步长。类型)，类似python的range,左闭右开
arr5 = np.arange(1,5,2 ,dtype = np.int32)
print(f'数组对象：{arr5}')
print(f'数组类型：{type(arr5)}')
print(f'数组元素类型：{arr5.dtype}')


## 3.4 matricx 生成二维数组

In [ ]:
# matrix()输入ndarray的子集，生成二维数组
arr6 = np.matrix('1,2;3,4;5,6')
print(f'数组对象：{arr6}')
print(f'数组类型：{type(arr6)}')
print(f'数组元素类型：{arr6.dtype}')

In [ ]:
arr7 = np.matrix([[1,2,3],[4,5,6]])
print(f'数组对象：{arr7}')
print(f'数组类型：{type(arr7)}')
print(f'数组元素类型：{arr7.dtype}')

## 3.5 rand(), randint(), uinform() 生成ndarray对象


In [ ]:
# rand()生成0.0-1.0之间的随机数组，左闭右开
arr8 = np.random.rand(2,3)
print(f'数组对象：{arr8}')
print(f'数组类型：{type(arr8)}')
print(f'数组元素类型：{arr8.dtype}')

In [ ]:
# randint()，生成指定范围之间的随机整数数组，仍然左闭右开
arr9 = np.random.randint(-1,5,size = (2,3))
print(f'数组对象：{arr9}')
print(f'数组类型：{type(arr9)}')
print(f'数组元素类型：{arr9.dtype}')

In [ ]:
# uniform()，生成指定范围之间的随机小数数组，仍然左闭右开
arr10 = np.random.uniform(-1,5,size = (2,3))
print(f'数组对象：{arr10}')
print(f'数组类型：{type(arr10)}')
print(f'数组元素类型：{arr10.dtype}')

## 3.6 通过astype函数将ndarray => ndarray


In [ ]:
# 1.创建一个float类型
arr11 = np.ones((2,3),dtype=np.float64)
print(f'数组对象：{arr11}')
print(f'数组类型：{type(arr11)}')
print(f'数组元素类型：{arr11.dtype}')
print()
arr12 = arr11.astype(np.int64)
print(f'数组对象：{arr12}')
print(f'数组类型：{type(arr12)}')
print(f'数组元素类型：{arr12.dtype}')




## 3.7 logspace等比数列和linspace等差数列


In [ ]:
# logspace(起始幂值，结束幂值，元素个数，base = 底数)
arr13 = np.logspace(0,5,10,base=2)
print(f'数组对象：{arr13}')
print(f'数组类型：{type(arr13)}')
print(f'数组元素类型：{arr13.dtype}')

In [ ]:
# linspace(起始值，结束值，元素个数，endpoint = True（默认）|False)
arr14 = np.linspace(0,5,5,endpoint= False)
print(f'数组对象：{arr14}')
print(f'数组类型：{type(arr14)}')
print(f'数组元素类型：{arr14.dtype}')
arr14 = np.linspace(0,5,5)
print(f'数组对象：{arr14}')
print(f'数组类型：{type(arr14)}')
print(f'数组元素类型：{arr14.dtype}')

# 4.numpy的内置函数

## 4.1基本函数

In [ ]:
arr = np.random.randn(2,3) # 获取一个标准的正态分布的2行3列数据
print(f'arr的值为{arr}')
# 演示基本函数
print(np.ceil(arr)) 
print(np.floor(arr))
print(np.rint(arr))
print(np.isnan(arr))
print(np.abs(arr))
print(np.multiply(arr,arr))
print(np.divide(arr,arr))
print(np.where(arr>0,1,-1))

## 4.2统计函数

In [ ]:
arr = np.arange(12).reshape((3,4))
print(f'元素内容:{arr}')
print(f'元素维度:{arr.shape}')

# 演示
print(np.mean(arr))
print(np.sum(arr))
print(np.max(arr))
print(np.min(arr))
print(np.std(arr))
print(np.var(arr))
print(np.argmax(arr))
print(np.argmin(arr))
print(np.cumsum(arr))
print(np.cumprod(arr))

In [ ]:
print(np.sum(arr,axis=0))
print(np.sum(arr,axis=1))
print(np.cumprod(arr,axis=1))

## 4.3 比较函数

In [ ]:
arr = np.random.randn(2,3)
print(arr)
print(np.any(arr>0))
print(np.all(arr>0))

## 4.4 排序函数


In [ ]:
arr = np.array([1,5,3,2,6])
print(f'排序前{arr}')
np.sort(arr)
print(f'第一种方式排序{arr}')
arr.sort()
print(f'第二种方式排序{arr}')

## 4.5去重函数

In [ ]:
arr = np.array([1,2,1,1,3,2,5])
print(f'去重前{arr}')
np.unique(arr)
print(f'去重后{arr}')
print(f'去重结果{np.unique(arr)}')


# 5. numpy运算

## 5.1 基本运算：对应元素直接运算

In [ ]:
arr1 = np.array([10,20,30,40])
arr2 = np.arange(4)
arr3 = arr1 * arr2

print(f'arr1:{arr1}')
print(f'arr2:{arr2}')
print(f'arr3:{arr3}')
print(np.multiply(arr1,arr2))

## 5.2 矩阵运算--1、行列数一致

In [38]:
arr1 = np.array([[1,2,3],[1,2,3]])
arr2 = np.array([[1,2,3],[1,2,3]])
arr3 = arr1*arr2
arr4 = np.multiply(arr1,arr2)
print(f'arr3:{arr3}')
print(f'arr4:{arr4}')


arr3:[[1 4 9]
 [1 4 9]]
arr4:[[1 4 9]
 [1 4 9]]


## 5.3 矩阵运算，行列数相反

In [40]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[9,8],[6,5],[3,2]])
print(arr1.dot(arr2))

[[30 24]
 [84 69]]
